// src/services/NotificationService.js

const auditLogger = require("../utils/auditLogger");

class NotificationService {
  constructor() {
    this.notificationRepository = null;
  }

  async initialize() {
    const { AppDataSource } = require("../main/db/datasource");
    const Notification = require("../entities/Notification");

    if (!AppDataSource.isInitialized) {
      await AppDataSource.initialize();
    }
    this.notificationRepository = AppDataSource.getRepository(Notification);
    console.log("NotificationService initialized");
  }

  async getRepository() {
    if (!this.notificationRepository) {
      await this.initialize();
    }
    return this.notificationRepository;
  }

  /**
   * Create a new notification (auto‑generated by backend)
   * @param {Object} data - { userId, title, message, type?, metadata? }
   * @param {string} [user="system"] - Who triggered the creation
   */
  async create(data, user = "system") {
    const {
      saveDb,
      updateDb,
      removeDb,
    } = require("../utils/dbUtils/dbActions");
    const repo = await this.getRepository();

    try {
      // @ts-ignore
      const notification = repo.create({
        // @ts-ignore
        title: data.title,
        // @ts-ignore
        message: data.message,
        // @ts-ignore
        type: data.type || "info",
        // @ts-ignore
        metadata: data.metadata || null,
        isRead: false,
        createdAt: new Date(),
      });

      // @ts-ignore
      const saved = await saveDb(repo, notification);
      await auditLogger.logCreate("Notification", saved.id, saved, user);
      console.log(
        // @ts-ignore
        `Notification created: ${data.title}`,
      );
      return saved;
    } catch (error) {
      // @ts-ignore
      console.error("Failed to create notification:", error.message);
      throw error;
    }
  }

  /**
   * Get a notification by ID
   * @param {number} id
   */
  // @ts-ignore
  async findById(id) {
    const repo = await this.getRepository();

    const where = { id };

    // @ts-ignore
    const notification = await repo.findOne({ where });
    if (!notification) {
      throw new Error(`Notification with ID ${id} not found`);
    }
    // @ts-ignore
    await auditLogger.logView("Notification", id, "system");
    return notification;
  }

  /**
   * Find all notifications for a user with filters and pagination
   * @param {Object} options - { isRead?, limit?, offset?, sortBy?, sortOrder? }
   */
  async findAll(options = {}) {
    const repo = await this.getRepository();

    // @ts-ignore
    const queryBuilder = repo.createQueryBuilder("notification");

    // @ts-ignore
    if (options.isRead !== undefined) {
      queryBuilder.andWhere("notification.isRead = :isRead", {
        // @ts-ignore
        isRead: options.isRead,
      });
    }

    // @ts-ignore
    const sortBy = options.sortBy || "createdAt";
    // @ts-ignore
    const sortOrder = options.sortOrder === "ASC" ? "ASC" : "DESC";
    queryBuilder.orderBy(`notification.${sortBy}`, sortOrder);

    // @ts-ignore
    if (options.limit) {
      // @ts-ignore
      queryBuilder.take(options.limit);
    }
    // @ts-ignore
    if (options.offset) {
      // @ts-ignore
      queryBuilder.skip(options.offset);
    }

    const notifications = await queryBuilder.getMany();
    await auditLogger.logView("Notification", null, "system");
    return notifications;
  }

  /**
   * Mark a single notification as read (or unread)
   * @param {number} id
   * @param {boolean} [isRead=true]
   * @param {string} [user="system"]
   */
  // @ts-ignore
  async markAsRead(id, isRead = true, user = "system") {
    const {
      saveDb,
      updateDb,
      removeDb,
    } = require("../utils/dbUtils/dbActions");
    const repo = await this.getRepository();

    const where = { id };

    // @ts-ignore
    const notification = await repo.findOne({ where });
    if (!notification) {
      throw new Error(`Notification with ID ${id} not found`);
    }

    const oldData = { ...notification };
    notification.isRead = isRead;
    notification.updatedAt = new Date();

    // @ts-ignore
    const saved = await updateDb(repo, notification);
    await auditLogger.logUpdate("Notification", id, oldData, saved, user);
    console.log(`Notification ${id} marked as ${isRead ? "read" : "unread"}`);
    return saved;
  }

  /**
   * Mark all notifications for a user as read
   * @param {string} [user="system"]
   */
  async markAllAsRead(user = "system") {
    const {
      saveDb,
      updateDb,
      removeDb,
    } = require("../utils/dbUtils/dbActions");
    const repo = await this.getRepository();

    // @ts-ignore
    const result = await repo
      .createQueryBuilder()
      .update()
      .set({ isRead: true, updatedAt: new Date() })
      .where("isRead = :isRead", {
        isRead: false,
      })
      .execute();

    const count = result.affected || 0;
    if (count > 0) {
      await auditLogger.logUpdate(
        "Notification",
        null,
        { isRead: false },
        { isRead: true },
        user,
      );
      console.log(`Marked ${count} notifications as read`);
    }
    return count;
  }

  /**
   * Delete a notification (hard delete)
   * @param {number} id
   * @param {string} [user="system"]
   */
  // @ts-ignore
  async delete(id, user = "system") {
    const {
      saveDb,
      updateDb,
      removeDb,
    } = require("../utils/dbUtils/dbActions");
    const repo = await this.getRepository();

    const where = { id };

    // @ts-ignore
    const notification = await repo.findOne({ where });
    if (!notification) {
      throw new Error(`Notification with ID ${id} not found`);
    }

    // @ts-ignore
    await removeDb(repo, notification);
    await auditLogger.logDelete("Notification", id, notification, user);
    console.log(`Notification ${id} deleted`);
    return { success: true };
  }

  /**
   * Get unread count for a user
   */
  async getUnreadCount() {
    const repo = await this.getRepository();
    // @ts-ignore
    return repo.count({ where: { isRead: false } });
  }

  /**
   * Get notification statistics for a user
   */
  async getStats() {
    const repo = await this.getRepository();

    // @ts-ignore
    const total = await repo.count();
    // @ts-ignore
    const unread = await repo.count({ where: { isRead: false } });
    const read = total - unread;

    // Count by type (optional)
    // @ts-ignore
    const typeCounts = await repo
      .createQueryBuilder("notification")
      .select("notification.type", "type")
      .addSelect("COUNT(*)", "count")
      .groupBy("notification.type")
      .getRawMany();

    return {
      total,
      unread,
      read,
      byType: typeCounts.reduce((acc, row) => {
        acc[row.type] = parseInt(row.count, 10);
        return acc;
      }, {}),
    };
  }
}

// Singleton instance
const notificationService = new NotificationService();
module.exports = notificationService;
